[package]
name        = "openppp3"
description = "openppp3 anti-censorship proxy (unified server/client binary)"
readme      = "../../README.md"
keywords    = ["anti-censorship", "network", "openppp2", "proxy"]
categories  = ["network-programming"]

version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
repository.workspace   = true
license.workspace      = true

[dependencies]
anyhow          = { workspace = true }
clap            = { workspace = true }
openppp3-client = { workspace = true }
openppp3-common = { workspace = true }
openppp3-server = { workspace = true }
spdlog-rs       = { workspace = true }

[lints]
workspace = true
