[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version      = "0.1.0"
edition      = "2024"
rust-version = "1.85"
license      = "MIT OR Apache-2.0"
repository   = "https://github.com/lxl66566/openppp3-rs"

[workspace.dependencies]
aes      = "0.8"
cfb-mode = "0.8"
chacha20 = "0.10"
ctr      = "0.9"
hkdf     = "0.12"
hmac     = "0.12"
rand     = "0.9"
sha2     = "0.10"
thiserror = "2"

# app crates
anyhow            = "1"
clap              = { version = "4", features = ["derive"] }
json5             = "0.4"
openppp3-core     = { path = "crates/core" }
openppp3-common   = { path = "crates/common" }
openppp3-server   = { path = "crates/server" }
openppp3-client   = { path = "crates/client" }
serde             = { version = "1", features = ["derive"] }
tracing           = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[workspace.lints.rust]
unsafe_code           = "warn"
unused_qualifications = "warn"

[workspace.lints.clippy]
all                     = { level = "warn", priority = -1 }
cargo                   = { level = "warn", priority = -1 }
doc_markdown            = "allow"
missing_errors_doc      = "allow"
missing_panics_doc      = "allow"
multiple_crate_versions = "allow"
pedantic                = { level = "warn", priority = -1 }
wildcard_imports        = "allow"

# If you are building bin target, uncomment this
# [profile.release]
# lto       = true
# opt-level = "s"
# panic     = "abort"
# strip     = true
