[workspace]
resolver = "3"
members  = ["crates/*"]

[workspace.package]
version      = "0.1.0"
edition      = "2024"
rust-version = "1.85"
repository   = "https://github.com/lxl66566/nextppp"
license      = "MIT OR Apache-2.0"

[workspace.dependencies]
aes       = "0.9"
cfb-mode  = "0.9"
chacha20  = "0.10"
ctr       = "0.10"
hkdf      = "0.13"
rand      = "0.10"
sha2      = "0.11"
thiserror = "2"

# bench / test only
criterion = "0.8"
libc      = "0.2"

# app crates
anyhow          = "1"
base94-simd     = { path = "crates/base94", version = "0.1.0" }
clap            = { version = "4", features = ["derive"] }
hotpath         = "0.23"
json5           = "1.3"
nextppp-client = { path = "crates/client" }
nextppp-common = { path = "crates/common" }
nextppp-core   = { path = "crates/core" }
nextppp-server = { path = "crates/server" }
serde           = { version = "1", features = ["derive"] }
spdlog-rs       = "0.5"

[workspace.lints.clippy]
all                     = { level = "warn", priority = -1 }
cargo                   = { level = "warn", priority = -1 }
doc_markdown            = "allow"
missing_errors_doc      = "allow"
missing_panics_doc      = "allow"
multiple_crate_versions = "allow"
pedantic                = { level = "warn", priority = -1 }
wildcard_imports        = "allow"

[workspace.lints.rust]
unsafe_code           = "warn"
unused_qualifications = "warn"

# If you are building bin target, uncomment this
[profile.release]
opt-level     = "s"
strip         = true
lto           = true
panic         = "unwind"
codegen-units = 1
