[package]
name         = "openppp3-server"
description  = "openppp3 anti-censorship proxy server"
readme       = "../../README.md"
keywords     = ["proxy", "anti-censorship", "network", "openppp2"]
categories   = ["network-programming"]

version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true

[dependencies]
openppp3-core   = { workspace = true }
openppp3-common = { workspace = true }
anyhow          = { workspace = true }
clap            = { workspace = true }
rand            = { workspace = true }
tracing         = { workspace = true }
tracing-subscriber = { workspace = true }

[lints]
workspace = true
